#############################################################################
######## Analysis and modeling of the MMM dataset generated with AMSS
#############################################################################

############################################################################
###### Data Pre-processing and plotting
############################################################################
library(ggplot2)

setwd("~/GitHub/MMM/Simple Example")

coffee_data = read.csv("mmm_data_amss_full.csv", header=T)

names(coffee_data)

# plot seasonality
plot(coffee_data$time.index, coffee_data$market.rate, type="l", xlab = "Week", ylab = "Market rate",
     main = "Market Rate Seasonality")

# plot tv spend
plot(coffee_data$time.index, coffee_data$tv.spend, type="l", xlab = "Week", ylab = "TV Spend ($MM)",
     main = "TV Spend")

# plot tv and search spend
plot(coffee_data$tv.spend,type = "l",col = "red", xlab = "Week", ylab = "Spend ($MM)", 
     main = "Media Spend")
lines(coffee_data$search.spend, type = "l", col = "blue")

# plot search impressions, query volume and clicks
layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))
plot(coffee_data$search.imps,type = "l",xlab = "Week", ylab = "imps", 
     main = "Search Impressions")
plot(coffee_data$search.query.volume, type = "l",xlab = "week", ylab = "volume",
     main = "Search Query Volume")
plot(coffee_data$search.clicks, type = "l", xlab= "week", ylab = "clicks",
     main = "Search Clicks")

dev.off()

# plot sales
plot(coffee_data$revenue,type = "l",xlab = "Week", ylab = "Revenue ($MM)", 
     main = "Sales Revenue")

# read in the dataset after the burn-in period
coffee_data = read.csv("mmm_data_amss.csv", header=T)

# read the base sales. base sales is generated by setting tv and search spend to zero
coffee_base = read.csv("base_sales.csv", header=T)

# merge base sales to original dataframe
names(coffee_base)[names(coffee_base) == "brand.sales"] <- "base.sales"
coffee = merge(coffee_data, coffee_base$base.sales)
names(coffee)[names(coffee) == "y"] <- "base.sales"

# create additional variables
coffee$tv.seas <- coffee$tv.spend * coffee$base.sales
coffee$search.seas <- coffee$search.spend * coffee$base.sales
coffee$tv.quad <- coffee$tv.spend^(1/2)
coffee$tv.cube <- coffee$tv.spend^(1/3)

# first model
lmcoffeesales <- lm(brand.sales ~ tv.spend + search.spend 
                    + base.sales + tv.seas + search.seas 
                    + tv.quad + tv.cube, data=coffee)

summary(lmcoffeesales)

names(lmcoffeesales)